# Generated by Django 3.1.5 on 2021-01-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='username',
            field=models.TextField(default='Muskan'),
        ),
    ]
